### PR TITLE
Added ss_extractor_cryo

### PR DESCRIPTION
**Pull request by VicenteTM**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by VicenteTM** [comment]
@conda-forge-admin, please ping conda-forge/help-python

**Comment by VicenteTM** [comment]
@conda-forge-admin, please ping conda-forge/help-python

**Comment by dopplershift** [comment]
It looks like your username in the maintainers for this recipe isn't quite right. Can you add your correct username following [our docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list)?

**Comment by dopplershift** [comment]
@VicenteTM @hung-chi You should both have invitations to join the conda-forge organization, which you'll need to accept to have the ability to merge the PR. If you don't see the invitations, please check your email spam folder.

**Pull request merged**
